# Generated by Django 5.2.14 on 2026-05-21 20:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('website_build', 'Website Build'), ('maintenance', 'Monthly Maintenance'), ('social_media', 'Social Media Management'), ('hosting', 'Hosting'), ('addon', 'Add-On')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_display', models.CharField(blank=True, help_text='Auto-generated from price if left blank — e.g. "$599/mo".', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('billing_interval', models.CharField(blank=True, help_text="'month', 'year', or blank for one-time.", max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('pages_included', models.IntegerField(blank=True, null=True)),
                ('practice_areas_included', models.IntegerField(blank=True, null=True)),
                ('timeline_weeks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TierFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.servicetier')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
