# Generated by Django 5.2.14 on 2026-05-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_addonpricing_servicetier_tierfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonpricing',
            name='included_in_plans',
            field=models.JSONField(blank=True, default=list, help_text="Plan slugs/codes where this add-on is included free, e.g. ['maintenance_growth', 'maintenance_dominant']."),
        ),
    ]
