# Generated by Django 5.2.14 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_addonpricing_included_in_plans'),
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniinvoice',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_invoices_new', to='clients.account'),
        ),
        migrations.AddField(
            model_name='miniinvoice',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_invoices_new', to='clients.website'),
        ),
    ]
