# Generated by Django 5.2.14 on 2026-06-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_miniinvoice_account_new_miniinvoice_website_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='max_channels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='reply_handling',
            field=models.CharField(blank=True, choices=[('none', 'You handle replies'), ('triage', 'Triage — we flag, you respond'), ('full', 'Full reply & DM management')], max_length=10),
        ),
    ]
