# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_cancellationreason'),
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniinvoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_invoices', to='clients.clientprofile'),
        ),
    ]
