# Generated by Django 5.2.14 on 2026-09-03 00:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_miniinvoice_client'),
        ('clients', '0060_alter_onboardinginvoice_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_started_at', models.DateTimeField()),
                ('stage', models.CharField(choices=[('email_3', 'Day 3 — payment failed email'), ('email_7', 'Day 7 — payment failed email'), ('email_14', 'Day 14 — payment failed email'), ('maintenance_14', 'Day 14 — site to maintenance page'), ('offline_21', 'Day 21 — droplet powered off'), ('destroy_30', 'Day 30 — droplet destroyed'), ('snapshot_delete_60', 'Day 60 — snapshot deleted')], max_length=32)),
                ('status', models.CharField(choices=[('done', 'Done'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='done', max_length=24)),
                ('detail', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_events', to='clients.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dunning_events', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dunning_events', to='clients.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'window_started_at'], name='billing_dun_account_feaf25_idx'), models.Index(fields=['status'], name='billing_dun_status_543035_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('website__isnull', True)), fields=('account', 'window_started_at', 'stage'), name='uniq_dunning_account_stage_per_window'), models.UniqueConstraint(condition=models.Q(('website__isnull', False)), fields=('account', 'website', 'window_started_at', 'stage'), name='uniq_dunning_site_stage_per_window')],
            },
        ),
    ]
