# Generated by Django 5.2.14 on 2026-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_dunningevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
