# Generated by Django 5.2.14 on 2026-09-21 10:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_servicetier_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeRevenueSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(default=0)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charge_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stripe Revenue Sync',
                'verbose_name_plural': 'Stripe Revenue Sync',
            },
        ),
    ]
