# Generated by Django 5.2.14 on 2026-05-21 03:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_site', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload_received', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=15)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(choices=[('moonieful', 'Moonieful'), ('aspired', 'Aspired')], max_length=20)),
                ('moonieful_client_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('client_created', 'Client Created'), ('client_updated', 'Client Updated'), ('revision_created', 'Revision Created'), ('stage_changed', 'Stage Changed'), ('project_complete', 'Project Complete'), ('document_added', 'Document Added'), ('maintenance_activated', 'Maintenance Activated')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
