# Generated by Django 5.2.14 on 2026-09-26 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_clientdocument_category_and_more'),
        ('sync', '0003_synclog_event_id_syncjob_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='clients.account'),
        ),
    ]
