# Generated by Django 5.2.14 on 2026-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('law_firm', 'Law Firm'), ('restaurant', 'Restaurant'), ('contractor', 'Contractor'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('technology', 'Technology'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, choices=[('google', 'Google Search'), ('referral', 'Referral'), ('social', 'Social Media'), ('cold_email', 'Cold Email'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
