# Generated by Django 5.2.14 on 2026-05-20 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('attorney_name', models.CharField(blank=True, max_length=255)),
                ('practice_area', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(default='Law Firm', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('google_review_count', models.IntegerField(default=0)),
                ('has_google_business', models.BooleanField(default=False)),
                ('website_performance_score', models.IntegerField(blank=True, null=True)),
                ('website_seo_score', models.IntegerField(blank=True, null=True)),
                ('website_mobile_score', models.IntegerField(blank=True, null=True)),
                ('website_issues', models.JSONField(blank=True, default=list)),
                ('audit_run_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('temperature', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('call_booked', 'Call Booked'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost'), ('unsubscribed', 'Unsubscribed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('state_bar', 'State Bar Directory'), ('contact_form', 'Contact Form'), ('audit_tool', 'Audit Tool'), ('manual', 'Manual Entry'), ('counsel_south', 'Counsel South')], default='manual', max_length=20)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('sequence_step', models.IntegerField(default=0)),
                ('sequence_paused', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('inquiry_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_level', models.IntegerField(choices=[(1, 'Level 1 — Approve every email'), (2, 'Level 2 — Auto-send cold, approve replies'), (3, 'Level 3 — Auto-send cold + simple replies'), (4, 'Level 4 — Full auto except flagged'), (5, 'Level 5 — Fully autonomous')], default=1)),
                ('daily_send_cap', models.IntegerField(default=15)),
                ('warming_start_date', models.DateField(blank=True, null=True)),
                ('outreach_active', models.BooleanField(default=False)),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outreach Settings',
                'verbose_name_plural': 'Outreach Settings',
            },
        ),
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suppression List Entry',
                'verbose_name_plural': 'Suppression List',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('sequence_step', models.IntegerField(default=1)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to='outreach.lead')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('wrong_person', 'Wrong Person'), ('maybe_later', 'Maybe Later'), ('already_have_someone', 'Already Have Someone'), ('question', 'Question — Needs You'), ('unclear', 'Unclear — Needs You'), ('hostile', 'Hostile — Needs You'), ('unsubscribe', 'Unsubscribe Request')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('needs_human', models.BooleanField(default=False)),
                ('handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('ai_suggested_reply', models.TextField(blank=True)),
                ('email_sent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outreach.emailsent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='outreach.lead')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='outreach.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
