# Generated by Django 5.2.14 on 2026-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
