# Generated by Django 5.2.14 on 2026-05-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_lead_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='copyright_year',
            field=models.IntegerField(blank=True, help_text="Year parsed from the footer's © string. Stale (3+ years old) is a scoring signal.", null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_generic_email',
            field=models.BooleanField(blank=True, help_text="True when the email we found lives on a free provider (gmail.com, yahoo.com, hotmail.com, aol.com, outlook.com) rather than the firm's own domain.", null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_ssl',
            field=models.BooleanField(blank=True, help_text='True when site is reachable on https://, False when only http:// works, NULL when not yet checked.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='other_social_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
