# Generated by Django 5.2.14 on 2026-05-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_lead_copyright_year_lead_enrichment_attempted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraveSearchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(unique=True)),
                ('query_count', models.IntegerField(default=0)),
                ('last_query_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brave Search Usage',
                'verbose_name_plural': 'Brave Search Usage',
                'ordering': ['-year_month'],
            },
        ),
    ]
