# Generated by Django 5.2.14 on 2026-05-30 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_bravesearchusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emailsent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailsent',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_replies', to='outreach.emailreply'),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='kind',
            field=models.CharField(choices=[('cold', 'Cold outreach'), ('reply', 'Reply')], default='cold', max_length=10),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='message_id_header',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved — waiting to send'), ('sent', 'Sent'), ('rejected', 'Rejected')], db_index=True, default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emailsent',
            index=models.Index(fields=['status', 'kind', '-created_at'], name='outreach_em_status_7f299d_idx'),
        ),
    ]
