# Generated by Django 5.2.14 on 2026-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_alter_emailsent_options_emailsent_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label shown on the scrape dashboard.', max_length=120)),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('texas_bar', 'Texas State Bar'), ('georgia_bar', 'Georgia State Bar')], max_length=20)),
                ('niche', models.CharField(help_text='Google Maps: free-text search niche (e.g. "personal injury lawyer", "dentist"). Bar scrapers: the practice area string exactly as it appears in the directory.', max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='TX or GA only (bar scrapers cover those two states).', max_length=2)),
                ('max_results', models.IntegerField(default=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_imported', models.IntegerField(default=0)),
                ('last_run_skipped', models.IntegerField(default=0)),
                ('last_run_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
