# Generated by Django 5.2.14 on 2026-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_scrapejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreply',
            name='inbound_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
