# Generated by Django 5.2.14 on 2026-06-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_emailreply_inbound_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='opted_in_addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='opted_in_addons_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
