# Generated by Django 5.2.14 on 2026-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0008_lead_opted_in_addons_lead_opted_in_addons_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_interest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
