# Generated by Django 5.2.14 on 2026-08-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0009_lead_service_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Security-first", "Slow site"', max_length=100)),
                ('sequence_step', models.IntegerField(db_index=True, help_text='Which of the 4 touches this is for (1-4).')),
                ('angle_instructions', models.TextField(help_text='The per-variant angle, appended to the shared system prompt at draft time. Editable without a deploy.')),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('proposed_by', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sends', models.IntegerField(default=0)),
                ('opens', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Template Variant',
                'verbose_name_plural': 'Email Template Variants',
                'ordering': ['sequence_step', 'name'],
            },
        ),
        migrations.AddField(
            model_name='outreachsettings',
            name='daily_ai_spend_cap_usd',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Hard daily USD ceiling for AI agent spend (Claude tokens + Apify runs). Set to 0 to stop the agent spending entirely.', max_digits=8),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='template_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='outreach.emailtemplatevariant'),
        ),
    ]
