# Generated by Django 5.2.14 on 2026-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0013_bump_llm_spend_cap_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refused', 'Refused — quota or budget')], default='running', max_length=20)),
                ('actor_id', models.CharField(max_length=64)),
                ('apify_run_id', models.CharField(blank=True, max_length=64)),
                ('dataset_id', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('search_input', models.JSONField(blank=True, default=dict)),
                ('results_requested', models.IntegerField(default=0)),
                ('results_returned', models.IntegerField(default=0)),
                ('leads_imported', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('actual_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Apify Run',
                'verbose_name_plural': 'Apify Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('state_bar', 'State Bar Directory'), ('contact_form', 'Contact Form'), ('audit_tool', 'Audit Tool'), ('manual', 'Manual Entry'), ('counsel_south', 'Counsel South'), ('apify', 'Apify')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='outreachsettings',
            name='apify_max_results_per_run',
            field=models.IntegerField(default=50, help_text='Maximum leads requested per Apify actor run. At $0.002/lead this is the main cost lever: 50 leads is ~$0.12 a run. The actor own default is 100000 — never let a run through without this clamp.'),
        ),
        migrations.AlterField(
            model_name='outreachsettings',
            name='apify_max_runs_per_day',
            field=models.IntegerField(default=1, help_text='Maximum Apify actor runs Prospect may start per day. Separate from the Claude spend cap on purpose — a runaway scrape must not eat the reasoning budget. 0 disables sourcing.'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(choices=[('apify', 'Apify — contacts with emails'), ('google_maps', 'Google Maps'), ('texas_bar', 'Texas State Bar'), ('georgia_bar', 'Georgia State Bar')], max_length=20),
        ),
    ]
