# Generated by Django 5.2.17 on 2026-08-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_apifyrun_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "TX — Personal Injury", "GA — Dental".', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('niche', models.CharField(help_text='Search term / industry, e.g. "personal injury lawyer".', max_length=120)),
                ('business_type', models.CharField(blank=True, help_text='Stamped onto imported leads. Blank = infer from source.', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('instantly_campaign_id', models.CharField(blank=True, db_index=True, help_text='Instantly campaign UUID. Blank means leads cannot be pushed yet — create the campaign in Instantly first.', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('leads_pushed', models.IntegerField(default=0)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outreach Campaign',
                'verbose_name_plural': 'Outreach Campaigns',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='email_verification_status',
            field=models.CharField(db_index=True, default='pending', help_text='Set by outreach.verify. Role addresses and hard-invalid mailboxes never reach a campaign.', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='icebreaker',
            field=models.TextField(blank=True, help_text='One personalised opening line, generated from enrichment signals. Pushed to Instantly as {{icebreaker}}.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='icebreaker_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='instantly_lead_id',
            field=models.CharField(blank=True, db_index=True, help_text="Instantly's own id, returned when the lead is pushed.", max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='pushed_to_instantly_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstantlyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reply_received', 'Reply received'), ('email_sent', 'Email sent'), ('email_opened', 'Email opened'), ('link_clicked', 'Link clicked'), ('email_bounced', 'Email bounced'), ('lead_unsubscribed', 'Lead unsubscribed'), ('lead_interested', 'Lead marked interested'), ('lead_not_interested', 'Lead marked not interested'), ('campaign_completed', 'Campaign completed for lead'), ('unknown', 'Unknown / unhandled')], db_index=True, default='unknown', max_length=40)),
                ('raw_event_type', models.CharField(blank=True, max_length=80)),
                ('lead_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantly_events', to='outreach.lead')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='outreach.outreachcampaign')),
            ],
            options={
                'verbose_name': 'Instantly Event',
                'verbose_name_plural': 'Instantly Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='outreach.outreachcampaign'),
        ),
    ]
