# Generated by Django 5.2.17 on 2026-08-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0015_outreachcampaign_lead_email_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='site_status',
            field=models.CharField(blank=True, db_index=True, help_text="'' = live site. Otherwise site_parked / site_unreachable / site_bot_blocked. Set by outreach.enricher.classify_site.", max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='tls_error',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
