# Generated by Django 5.2.17 on 2026-08-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0017_lead_needs_review_lead_review_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReviewQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Lead awaiting review',
                'verbose_name_plural': 'Leads awaiting review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('outreach.lead',),
        ),
    ]
