# Generated by Django 5.2.17 on 2026-08-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0018_leadreviewqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='founded_year',
            field=models.IntegerField(blank=True, help_text='Year the firm was founded, when the source supplies it.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='practice_areas',
            field=models.CharField(blank=True, help_text='Comma-separated, from the source. e.g. "estate planning, probate".', max_length=500),
        ),
    ]
