# Generated by Django 5.2.17 on 2026-08-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0019_lead_founded_year_lead_practice_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier, e.g. "security_review".', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Shown in the admin and campaign names.', max_length=120)),
                ('appeals_to', models.CharField(blank=True, help_text='What motivation this offer targets. Keeps the set genuinely different rather than six rewordings.', max_length=120)),
                ('fulfilment_cost', models.TextField(blank=True, help_text='Honest note on what honouring this costs YOU. Read it before scaling an offer that is working.')),
                ('pitch', models.TextField(help_text='Touch 1: the full offer, in your voice.')),
                ('restate', models.TextField(help_text='Touch 2: the offer in one clause, no leading capital. Reads as "...what I am offering: <restate>."')),
                ('ask', models.TextField(help_text='The one-line, low-friction call to action.')),
                ('active', models.BooleanField(db_index=True, default=False, help_text='False = proposed, awaiting approval. Default False so nothing an agent writes can start sending itself.')),
                ('proposed_by', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=20)),
                ('sends', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('positive_replies', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Null falls back to the default offer at build time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='outreach.offer'),
        ),
    ]
