# Generated by Django 5.2.17 on 2026-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0020_offer_outreachcampaign_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachsettings',
            name='instantly_sending_enabled',
            field=models.BooleanField(default=False, help_text='OFF until the sending mailboxes are warmed. Turning it on does NOT bypass the warmup check - both must pass before any lead is pushed to a campaign.'),
        ),
        migrations.AddField(
            model_name='outreachsettings',
            name='min_ready_mailboxes',
            field=models.IntegerField(default=3, help_text='How many mailboxes must pass before sending is allowed. Rotation needs more than one.'),
        ),
        migrations.AddField(
            model_name='outreachsettings',
            name='min_warmup_days',
            field=models.IntegerField(default=14, help_text='Days a mailbox must have been warming, regardless of its score.'),
        ),
        migrations.AddField(
            model_name='outreachsettings',
            name='min_warmup_score',
            field=models.IntegerField(default=90, help_text='Mailboxes below this score do not count toward the readiness check.'),
        ),
    ]
