# Generated by Django 5.2.17 on 2026-08-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0021_outreachsettings_instantly_sending_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='lead_target',
            field=models.PositiveIntegerField(default=0, help_text='Stop assigning leads to this arm once it holds this many. 0 = unlimited. Use 300-400 per arm for a readable A/B.'),
        ),
    ]
