# Generated by Django 5.2.17 on 2026-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0022_outreachcampaign_lead_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='google_profile_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_profile_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outreachsettings',
            name='places_max_lookups_per_day',
            field=models.IntegerField(default=150, help_text='Maximum Google Places profile lookups per day. Only ever spent on QUALIFIED leads — verified, contactable, and not held for review. 0 disables the lookup.'),
        ),
    ]
