# Generated by Django 5.2.14 on 2026-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0024_apifyrun_results_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='niche_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='niche_evidence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='niche_verdict',
            field=models.CharField(choices=[('pending', 'Not checked yet'), ('confirmed', 'Confirmed in niche'), ('rejected', 'Rejected — different kind of business'), ('unconfirmed', 'Unconfirmed — page and name said nothing')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='site_summary',
            field=models.TextField(blank=True),
        ),
    ]
