# Generated by Django 5.2.14 on 2026-10-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0025_lead_niche_checked_at_lead_niche_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ghl_contact_id',
            field=models.CharField(blank=True, db_index=True, help_text="GoHighLevel's own id, returned by /contacts/upsert.", max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='pushed_to_ghl_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FailedLeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, help_text='The GHL request body that failed to send.')),
                ('error', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False, help_text='Manually pushed to GHL by hand / confirmed not needed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_ghl_submissions', to='outreach.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
