# Generated by Django 5.2.14 on 2026-05-21 03:04

import clients.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('business_type', models.CharField(blank=True, help_text='Blank for Moonieful-synced clients — never the Law Firm default.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('package', models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred')], max_length=30)),
                ('moonieful_client_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('synced_from_moonieful', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_conflict_flagged', models.BooleanField(default=False)),
                ('moonieful_package', models.CharField(blank=True, help_text='The package Miki sold them.', max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('maintenance_active', models.BooleanField(default=False)),
                ('maintenance_started_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff only — never shown to the client.')),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('structure', 'Structure'), ('design', 'Design'), ('content', 'Content'), ('review', 'Review'), ('revisions', 'Revisions'), ('pre_launch', 'Pre-Launch'), ('live', 'Live')], default='intake', max_length=20)),
                ('package', models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build')], max_length=20)),
                ('staging_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('support_window_ends', models.DateField(blank=True, help_text='Launch date + 14 days.', null=True)),
                ('payment_status', models.CharField(choices=[('awaiting_deposit', 'Awaiting Deposit'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid')], default='awaiting_deposit', max_length=20)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('final_paid_at', models.DateTimeField(blank=True, null=True)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('revision_limit', models.PositiveIntegerField(default=2)),
                ('moonieful_referred', models.BooleanField(default=False)),
                ('moonieful_handoff_at', models.DateTimeField(blank=True, null=True)),
                ('moonieful_stage_history', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brand_colors', models.CharField(blank=True, max_length=255)),
                ('brand_fonts', models.CharField(blank=True, max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='portal/intake/logos/')),
                ('photos_provided', models.BooleanField(default=False)),
                ('photos_note', models.TextField(blank=True)),
                ('about_copy', models.TextField(blank=True)),
                ('practice_areas', models.TextField(blank=True)),
                ('attorney_bios', models.TextField(blank=True)),
                ('reference_sites', models.TextField(blank=True)),
                ('competitors', models.TextField(blank=True)),
                ('domain_name', models.CharField(blank=True, max_length=255)),
                ('domain_registrar', models.CharField(blank=True, choices=[('namecheap', 'Namecheap'), ('godaddy', 'GoDaddy'), ('google_domains', 'Google Domains'), ('cloudflare', 'Cloudflare'), ('other', 'Other')], max_length=30)),
                ('google_business_access', models.BooleanField(default=False)),
                ('social_links', models.TextField(blank=True)),
                ('moonieful_intake_raw', models.JSONField(blank=True, default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clients.project')),
            ],
            options={
                'verbose_name': 'Intake Response',
                'verbose_name_plural': 'Intake Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('to_client', 'To Client'), ('from_client', 'From Client')], max_length=20)),
                ('file', models.FileField(upload_to=clients.models.client_document_path)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('moonieful_document_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clientprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.project')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('set_by', models.CharField(blank=True, help_text='Who triggered this transition (staff name, "system", "sync").', max_length=255)),
                ('client_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='clients.project')),
            ],
            options={
                'verbose_name': 'Project Stage Log',
                'verbose_name_plural': 'Project Stage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('aspired_portal', 'Aspired Portal'), ('moonieful_portal', 'Moonieful Portal'), ('email', 'Email')], default='aspired_portal', max_length=20)),
                ('description', models.TextField()),
                ('is_major', models.BooleanField(default=True)),
                ('counts_against_limit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('out_of_scope', 'Out of Scope')], default='pending', max_length=20)),
                ('moonieful_revision_id', models.UUIDField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='clients.project')),
            ],
            options={
                'verbose_name': 'Revision Request',
                'verbose_name_plural': 'Revision Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.clientprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.project')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
