# Generated by Django 5.2.14 on 2026-05-21 03:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.CharField(choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build')], max_length=20)),
                ('build_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline_weeks', models.IntegerField(default=4)),
                ('contract_text', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_name', models.CharField(blank=True, max_length=200)),
                ('contract_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
