# Generated by Django 5.2.14 on 2026-05-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='notify_on_stage_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], default='email', max_length=10),
        ),
    ]
