# Generated by Django 5.2.14 on 2026-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_notify_on_stage_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='do_droplet_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='do_droplet_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='do_droplet_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
