# Generated by Django 5.2.14 on 2026-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_do_droplet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='handoff_followup_sent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
