# Generated by Django 5.2.14 on 2026-05-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientprofile_handoff_followup_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='client_pin_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_pin_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_pin_lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_pin_salt',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
