# Generated by Django 5.2.14 on 2026-05-22 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientprofile_client_pin_failed_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChangelogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('page_added', 'Page Added'), ('page_updated', 'Page Updated'), ('security_patch', 'Security Patch'), ('dependency_update', 'Dependency Update'), ('blog_published', 'Blog Post Published'), ('image_optimization', 'Image Optimization'), ('seo_update', 'SEO Update'), ('bug_fix', 'Bug Fix'), ('performance', 'Performance Improvement'), ('deployment', 'Deployment'), ('content_update', 'Content Update'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(help_text='Short summary shown as the entry label.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation shown on expand.')),
                ('url_changed', models.URLField(blank=True, help_text='Optional — the specific page that was changed.')),
                ('is_client_visible', models.BooleanField(default=True, help_text='Untick to keep this entry internal — never shown to the client.')),
                ('date_of_change', models.DateField(default=django.utils.timezone.localdate, help_text='Defaults to today; can be backdated.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Site Changelog Entry',
                'verbose_name_plural': 'Site Changelog Entries',
                'ordering': ['-date_of_change', '-created_at'],
            },
        ),
    ]
