# Generated by Django 5.2.14 on 2026-05-22 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_sitechangelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=3)),
                ('is_resolved', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_alerts', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-alerted_at'],
            },
        ),
        migrations.CreateModel(
            name='UptimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_records', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['client', 'checked_at'], name='clients_upt_client__f4ac6c_idx')],
            },
        ),
    ]
