# Generated by Django 5.2.14 on 2026-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_uptimealert_uptimerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='testimonial_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='testimonial_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='testimonial_url',
            field=models.URLField(blank=True),
        ),
    ]
