# Generated by Django 5.2.14 on 2026-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clientprofile_testimonial_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
