# Generated by Django 5.2.14 on 2026-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientprofile_address_clientprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='auto_send_scan_reports',
            field=models.BooleanField(default=False),
        ),
    ]
