# Generated by Django 5.2.14 on 2026-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientprofile_auto_send_scan_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
