# Generated by Django 5.2.14 on 2026-05-23 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientprofile_is_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_month', models.DateField(help_text='First day of the month, e.g. 2026-05-01.', unique=True)),
                ('mrr_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrr_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrr_churned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrr_net_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_maintenance_clients', models.IntegerField(default=0)),
                ('active_project_clients', models.IntegerField(default=0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('one_time_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Revenue Snapshot',
                'verbose_name_plural': 'Revenue Snapshots',
                'ordering': ['-snapshot_month'],
            },
        ),
        migrations.CreateModel(
            name='ClientHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('payment_score', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('nps_score_component', models.IntegerField(default=0)),
                ('uptime_score', models.IntegerField(default=0)),
                ('support_score', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('critical', 'Critical')], default='healthy', max_length=10)),
                ('churn_risk', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Health Score',
                'verbose_name_plural': 'Client Health Scores',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['client', '-calculated_at'], name='clients_cli_client__979f21_idx'), models.Index(fields=['health_status', '-calculated_at'], name='clients_cli_health__49eb38_idx')],
            },
        ),
    ]
