# Generated by Django 5.2.14 on 2026-05-23 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_revenuesnapshot_clienthealthscore'),
        ('outreach', '0002_lead_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('metric_1_label', models.CharField(blank=True, max_length=100)),
                ('metric_1_value', models.CharField(blank=True, max_length=50)),
                ('metric_2_label', models.CharField(blank=True, max_length=100)),
                ('metric_2_value', models.CharField(blank=True, max_length=50)),
                ('metric_3_label', models.CharField(blank=True, max_length=100)),
                ('metric_3_value', models.CharField(blank=True, max_length=50)),
                ('testimonial_quote', models.TextField(blank=True)),
                ('testimonial_name', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('total_reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Referral Link',
                'verbose_name_plural': 'Referral Links',
                'ordering': ['-conversions', '-leads_generated'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect_name', models.CharField(max_length=200)),
                ('prospect_email', models.EmailField(blank=True, max_length=254)),
                ('prospect_business', models.CharField(blank=True, max_length=200)),
                ('prospect_city', models.CharField(blank=True, max_length=100)),
                ('prospect_state', models.CharField(blank=True, max_length=50)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('project_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maintenance_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('goals', models.TextField(blank=True)),
                ('pain_points', models.TextField(blank=True)),
                ('case_study_ids', models.JSONField(blank=True, default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='outreach.lead')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='clients_pro_status_90f4ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('click', 'Link Click'), ('lead', 'Lead Created'), ('conversion', 'Client Converted')], max_length=15)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('reward_given', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_note', models.CharField(blank=True, max_length=200)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to='outreach.lead')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.referrallink')),
            ],
            options={
                'verbose_name': 'Referral Event',
                'verbose_name_plural': 'Referral Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referral_link', '-created_at'], name='clients_ref_referra_ac04b1_idx'), models.Index(fields=['event_type', '-created_at'], name='clients_ref_event_t_57b29f_idx')],
            },
        ),
    ]
