# Generated by Django 5.2.14 on 2026-05-23 17:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_casestudy_referrallink_proposal_referralevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.DateField(help_text='First day of the month, e.g. 2026-05-01.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('suggestions_count', models.IntegerField(default=0)),
                ('overall_assessment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('no_suggestions', 'No Suggestions')], default='complete', max_length=20)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Intelligence Report',
                'verbose_name_plural': 'Intelligence Reports',
                'ordering': ['-report_month'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion_type', models.CharField(choices=[('seo', 'SEO Improvement'), ('performance', 'Performance'), ('content', 'Content Update'), ('security', 'Security Fix'), ('conversion', 'Conversion Optimization'), ('keyword', 'Keyword Opportunity'), ('competitor', 'Competitor Gap'), ('technical', 'Technical Issue'), ('design', 'Design Update'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('expected_impact', models.TextField(blank=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('one_time_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maintenance_equivalent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Admin Review'), ('approved_to_send', 'Approved to Send'), ('sent_to_client', 'Sent to Client'), ('client_approved', 'Client Approved'), ('client_declined', 'Client Declined'), ('in_scope', 'In Scope — Approved'), ('out_of_scope_offered', 'Out of Scope — Offer Sent'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], default='pending_review', max_length=25)),
                ('is_in_maintenance_scope', models.BooleanField(default=False)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('stripe_invoice_url', models.URLField(blank=True)),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('client_responded_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.CharField(blank=True, max_length=300)),
                ('response_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_suggestions', to='clients.clientprofile')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='clients.intelligencereport')),
            ],
            options={
                'verbose_name': 'Intelligence Suggestion',
                'verbose_name_plural': 'Intelligence Suggestions',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['client', '-report_month'], name='clients_int_client__945ced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intelligencereport',
            unique_together={('client', 'report_month')},
        ),
        migrations.AddIndex(
            model_name='intelligencesuggestion',
            index=models.Index(fields=['status', '-generated_at'], name='clients_int_status_7b7b49_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesuggestion',
            index=models.Index(fields=['client', '-generated_at'], name='clients_int_client__d16185_idx'),
        ),
    ]
