# Generated by Django 5.2.14 on 2026-05-23 19:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_intelligencereport_intelligencesuggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_year', models.IntegerField(help_text='Calendar year covered, e.g. 2025.')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed')], default='generating', max_length=15)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('executive_summary', models.TextField(blank=True)),
                ('year_in_review', models.TextField(blank=True)),
                ('looking_ahead', models.TextField(blank=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Annual Report',
                'verbose_name_plural': 'Annual Reports',
                'ordering': ['-report_year'],
                'indexes': [models.Index(fields=['client', '-report_year'], name='clients_ann_client__d834c6_idx'), models.Index(fields=['status', '-created_at'], name='clients_ann_status_f0e5ff_idx')],
                'unique_together': {('client', 'report_year')},
            },
        ),
    ]
