# Generated by Django 5.2.14 on 2026-05-23 19:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompetitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Competitor',
                'verbose_name_plural': 'Client Competitors',
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('client', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorGapReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.DateField(help_text='First day of the month, e.g. 2026-05-01.')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed'), ('no_competitors', 'No Competitors Set')], default='generating', max_length=20)),
                ('client_pages', models.JSONField(blank=True, default=list)),
                ('competitor_data', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('overall_assessment', models.TextField(blank=True)),
                ('total_gaps_found', models.IntegerField(default=0)),
                ('high_priority_gaps', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('admin_notified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_gap_reports', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Competitor Gap Report',
                'verbose_name_plural': 'Competitor Gap Reports',
                'ordering': ['-report_month'],
                'indexes': [models.Index(fields=['client', '-report_month'], name='clients_com_client__8ea5cf_idx'), models.Index(fields=['status', '-report_month'], name='clients_com_status_bff0e3_idx')],
                'unique_together': {('client', 'report_month')},
            },
        ),
    ]
