# Generated by Django 5.2.14 on 2026-05-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_clientcompetitor_competitorgapreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='session_recording_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
