# Generated by Django 5.2.14 on 2026-05-24 16:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clientprofile_session_recording_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_setup', 'Pending Account Setup'), ('pending_intake', 'Pending Intake'), ('onboarding_complete', 'Complete')], default='onboarding_complete', help_text='Gate state for the client portal. NEW admin-invoice flow sets this to pending_setup explicitly; default is onboarding_complete so legacy paths (contract-signing, Moonieful sync, manual admin creation) and the existing portal continue to work without the gate.', max_length=30),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='OnboardingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('setup_reminders_sent', models.IntegerField(default=0)),
                ('last_setup_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('intake_reminders_sent', models.IntegerField(default=0)),
                ('last_intake_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_token', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Onboarding Token',
                'verbose_name_plural': 'Onboarding Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
