# Generated by Django 5.2.14 on 2026-05-24 17:02

import clients.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_clientprofile_onboarding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='domain_registrar_other',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='google_business_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='social_links',
            field=models.TextField(blank=True, help_text='Catch-all for any social profiles not in the four standard fields.'),
        ),
        migrations.CreateModel(
            name='IntakePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=clients.models.intake_photo_path)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clients.intakeresponse')),
            ],
            options={
                'verbose_name': 'Intake Photo',
                'verbose_name_plural': 'Intake Photos',
                'ordering': ['created_at'],
            },
        ),
    ]
