# Generated by Django 5.2.14 on 2026-05-24 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_intakeresponse_domain_registrar_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=255)),
                ('payment_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_pdf_path', models.CharField(blank=True, max_length=500)),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invoice', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Onboarding Invoice',
                'verbose_name_plural': 'Onboarding Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
