# Generated by Django 5.2.14 on 2026-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_onboardinginvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='no_logo_yet',
            field=models.BooleanField(default=False),
        ),
    ]
