# Generated by Django 5.2.14 on 2026-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_intakeresponse_no_logo_yet'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='needs_admin_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
