# Generated by Django 5.2.14 on 2026-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_clientprofile_admin_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='stripe_hosting_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
