# Generated by Django 5.2.14 on 2026-05-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_clientprofile_stripe_hosting_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='maintenance_upsell_log',
            field=models.JSONField(blank=True, default=dict, help_text='Touchpoint -> ISO timestamp map for the maintenance upsell nudge cadence.'),
        ),
    ]
