# Generated by Django 5.2.14 on 2026-05-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_clientprofile_maintenance_upsell_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='final_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='moonieful_handoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='moonieful_stage_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_deposit', 'Awaiting Deposit'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid')], default='awaiting_deposit', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='revision_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='revisions_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='stage',
            field=models.CharField(choices=[('intake', 'Intake'), ('structure', 'Structure'), ('design', 'Design'), ('content', 'Content'), ('review', 'Review'), ('revisions', 'Revisions'), ('pre_launch', 'Pre-Launch'), ('live', 'Live')], default='intake', help_text='Where this client is in the build lifecycle.', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='staging_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='support_window_ends',
            field=models.DateField(blank=True, help_text='Launch date + 14 days.', null=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='projectstagelog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clients.project'),
        ),
        migrations.AlterField(
            model_name='projectstagelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='clients.project'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='clients.project'),
        ),
    ]
