# Generated by Django 5.2.14 on 2026-06-08 22:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('build', 'Provisioned for a build'), ('move_over', 'Move-over from existing host'), ('self_provision', 'Self-provisioned by customer')], default='build', max_length=20)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('maintenance', 'Maintenance mode (503)'), ('offline', 'Offline'), ('destroyed', 'Destroyed')], default='provisioning', max_length=20)),
                ('do_droplet_id', models.CharField(blank=True, max_length=40)),
                ('do_droplet_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('do_region', models.CharField(blank=True, default='nyc1', max_length=20)),
                ('do_size', models.CharField(blank=True, max_length=40)),
                ('do_snapshot_id', models.CharField(blank=True, max_length=40)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droplets', to='clients.account')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droplets', to='clients.website')),
            ],
            options={
                'ordering': ['-provisioned_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_site_url', models.URLField(blank=True)),
                ('tier_slug', models.CharField(choices=[('maintenance-essentials', 'Essentials'), ('maintenance-growth', 'Growth'), ('maintenance-dominant', 'Dominant')], default='maintenance-essentials', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused — paid but suspended'), ('cancelled', 'Cancelled — at period end'), ('ended', 'Ended — fully cancelled')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hosting_move_over', models.BooleanField(default=False)),
                ('hosting_move_over_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='clients.account')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='clients.website')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_slug', models.CharField(choices=[('social-basic', 'Basic'), ('social-standard', 'Standard'), ('social-full', 'Full Management')], default='social-basic', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled — at period end'), ('ended', 'Ended')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('max_channels', models.IntegerField(default=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_plans', to='clients.account')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('other', 'Other')], max_length=20)),
                ('handle', models.CharField(help_text='Account URL or @handle.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active — posting'), ('dormant', 'Has account, dormant'), ('pending', 'Need to create')], default='active', max_length=20)),
                ('follower_count', models.CharField(blank=True, help_text='Free text — "approximately 2,500".', max_length=40)),
                ('access_method', models.CharField(blank=True, choices=[('meta_bm', 'Meta Business Manager invite'), ('linkedin_admin', 'LinkedIn page admin'), ('vault_share', 'Direct login via vault'), ('defer', 'Will figure it out later')], max_length=30)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='clients.socialmediaplan')),
            ],
            options={
                'ordering': ['plan', 'platform'],
            },
        ),
    ]
