# Generated by Django 5.2.14 on 2026-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_backfill_service_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='do_snapshot_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_failure_offenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_failure_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='site_status',
            field=models.CharField(choices=[('live', 'Live'), ('maintenance', 'Maintenance (503)'), ('offline', 'Offline (powered down)'), ('destroyed', 'Droplet destroyed')], default='live', max_length=20),
        ),
    ]
