# Generated by Django 5.2.14 on 2026-06-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_clientprofile_do_snapshot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
