# Generated by Django 5.2.14 on 2026-06-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_contract_signed_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialchannel',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('gbp', 'Google Business Profile'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('other', 'Other')], max_length=20),
        ),
    ]
