# Generated by Django 5.2.14 on 2026-06-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_alter_socialchannel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gbp_location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialchannel',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('other', 'Other')], max_length=20),
        ),
    ]
