# Generated by Django 5.2.14 on 2026-06-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_clientprofile_gbp_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='comp_notes',
            field=models.TextField(blank=True, help_text='Why this client is comped — internal note.'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='comp_package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred')], max_length=30),
        ),
    ]
