# Generated by Django 5.2.14 on 2026-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_backfill_comp_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='stripe_social_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
