# Generated by Django 5.2.14 on 2026-06-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_clientprofile_stripe_social_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaplan',
            name='external_site_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_plans', to='clients.website'),
        ),
    ]
