# Generated by Django 5.2.14 on 2026-06-12 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_socialmediaplan_external_site_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.account'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='build_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('build', 'Website Development'), ('maintenance', 'Website Maintenance'), ('social', 'Social Media Marketing')], max_length=20)),
                ('tier_slug', models.CharField(max_length=50)),
                ('tier_name', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('billing_interval', models.CharField(blank=True, help_text="'month', 'year', or '' (one-time)", max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.contract')),
            ],
            options={
                'ordering': ['service_type'],
                'unique_together': {('contract', 'service_type')},
            },
        ),
    ]
