# Generated by Django 5.2.14 on 2026-06-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_contract_account_alter_contract_build_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_invoices', to='clients.contract'),
        ),
        migrations.AddField(
            model_name='onboardinginvoice',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
