# Generated by Django 5.2.14 on 2026-06-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_onboardinginvoice_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='lifecycle_status',
            field=models.CharField(blank=True, choices=[('inquiry', 'New inquiry — no contract'), ('contract_sent', 'Contract sent — unsigned'), ('contract_signed', 'Signed — awaiting deposit'), ('deposit_paid', 'Deposit paid'), ('in_build', 'In build'), ('live', 'Live')], help_text='Web-dev sales funnel state (set at booking + each step).', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='opted_in_maintenance_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='opted_in_social_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
