# Generated by Django 5.2.14 on 2026-06-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_website_lifecycle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='awaiting_invoice_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='discount_duration',
            field=models.CharField(blank=True, choices=[('once', 'First month only'), ('forever', 'Forever')], max_length=10),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='awaiting_invoice_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='discount_duration',
            field=models.CharField(blank=True, choices=[('once', 'First month only'), ('forever', 'Forever')], max_length=10),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('awaiting_payment', 'Awaiting payment'), ('paused', 'Paused — paid but suspended'), ('cancelled', 'Cancelled — at period end'), ('ended', 'Ended — fully cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediaplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('awaiting_payment', 'Awaiting payment'), ('paused', 'Paused'), ('cancelled', 'Cancelled — at period end'), ('ended', 'Ended')], default='active', max_length=20),
        ),
    ]
