# Generated by Django 5.2.14 on 2026-06-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_maintenanceplan_awaiting_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='final_invoice_url',
            field=models.URLField(blank=True),
        ),
    ]
