# Generated by Django 5.2.14 on 2026-06-13 02:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_website_final_invoice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deposit', 'Website Deposit'), ('final', 'Website Final Payment'), ('build', 'Website Payment'), ('maintenance', 'Maintenance'), ('social', 'Social Media'), ('hosting', 'Hosting'), ('addon', 'Add-on / Out-of-scope'), ('other', 'Payment')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='clients.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='clients.clientprofile')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='clients.website')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
    ]
