# Generated by Django 5.2.14 on 2026-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_property_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_stream_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
