# Generated by Django 5.2.14 on 2026-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_website_ga4_measurement_id_website_ga4_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='gmb_status',
            field=models.CharField(blank=True, choices=[('have', 'I have a Google Business Profile'), ('need', "I don't have one yet"), ('decline', "I don't want you to manage it")], max_length=10),
        ),
    ]
