# Generated by Django 5.2.14 on 2026-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_intakeresponse_gmb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comp_build_package',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='comp_maintenance_package',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='comp_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='comp_social_tier',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
