# Generated by Django 5.2.14 on 2026-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_account_comp_build_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='pending_tier_effective',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='pending_tier_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='pending_tier_effective',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaplan',
            name='pending_tier_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
