# Generated by Django 5.2.14 on 2026-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_maintenanceplan_pending_tier_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='card_gradient',
            field=models.CharField(blank=True, default='gradient-blue', help_text='CSS class for the card visual, e.g. gradient-blue.', max_length=40),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='live_url',
            field=models.URLField(blank=True, help_text='The published client site, if public.'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL segment for /portfolio/<slug>/. Leave blank to auto-generate from the title.', max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='summary',
            field=models.CharField(blank=True, help_text='One-line description used on the portfolio card and as the meta description.', max_length=300),
        ),
    ]
