# Generated by Django 5.2.14 on 2026-08-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_casestudy_card_gradient_casestudy_live_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of the live site, 16:10 to match the card. Captured by `capture_case_study_screenshots`; falls back to card_gradient when empty.', upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='card_gradient',
            field=models.CharField(blank=True, default='gradient-blue', help_text='CSS class for the card visual, e.g. gradient-blue. Used when no screenshot is set.', max_length=40),
        ),
    ]
