# Generated by Django 5.2.14 on 2026-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_casestudy_screenshot_alter_casestudy_card_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='multi_website_review_note',
            field=models.TextField(blank=True, help_text='What the mapping decided, and who decided it.'),
        ),
        migrations.AddField(
            model_name='account',
            name='multi_website_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When an operator signed off the explicit legacy-row → Website mapping for this multi-website account.', null=True),
        ),
    ]
