# Generated by Django 5.2.14 on 2026-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_account_multi_website_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='engagement_type',
            field=models.CharField(blank=True, choices=[('built', 'Built by Aspired'), ('redesigned', 'Redesigned by Aspired'), ('maintained', 'Maintained and improved by Aspired'), ('consulted', 'Consulting engagement')], help_text='What Aspired did for this client. Leave blank if it has not been verified — public copy then stays neutral instead of claiming a build.', max_length=20),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='platform',
            field=models.CharField(blank=True, help_text='e.g. "WordPress". Blank when not relevant.', max_length=60),
        ),
    ]
