# Generated by Django 5.2.14 on 2026-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_casestudy_engagement_type_casestudy_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='payment_verification_note',
            field=models.TextField(blank=True, help_text='How the payment was made and how it was confirmed.'),
        ),
        migrations.AddField(
            model_name='website',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When an operator confirmed payment that the ledger cannot show (e.g. paid outside Stripe).', null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='payment_verified_by',
            field=models.CharField(blank=True, help_text='Who confirmed it.', max_length=120),
        ),
    ]
