# Generated by Django 5.2.14 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_website_payment_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_failure_offenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_failure_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_social_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='do_snapshot_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='gbp_location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='site_status',
            field=models.CharField(choices=[('live', 'Live'), ('maintenance', 'Maintenance (503)'), ('offline', 'Offline (powered down)'), ('destroyed', 'Droplet destroyed')], default='live', max_length=20),
        ),
    ]
