# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_account_payment_failure_offenses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualreport',
            unique_together={('website_new', 'report_year')},
        ),
        migrations.AlterUniqueTogether(
            name='clientcompetitor',
            unique_together={('website_new', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='competitorgapreport',
            unique_together={('website_new', 'report_month')},
        ),
        migrations.AlterUniqueTogether(
            name='intelligencereport',
            unique_together={('website_new', 'report_month')},
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clientcompetitor',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clienthealthscore',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='competitorgapreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_gap_reports', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='intelligencereport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='intelligencesuggestion',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_suggestions', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='onboardinginvoice',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invoice', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='onboardingtoken',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_token', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='sitechangelogentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='uptimealert',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uptime_alerts', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='uptimerecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uptime_records', to='clients.clientprofile'),
        ),
    ]
