# Generated by Django 5.2.14 on 2026-08-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comp_build_package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build')], max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='comp_maintenance_package',
            field=models.CharField(blank=True, choices=[('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred')], max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='comp_social_tier',
            field=models.CharField(blank=True, choices=[('social-basic', 'Social — Basic'), ('social-standard', 'Social — Standard'), ('social-full', 'Social — Full Management')], max_length=30),
        ),
    ]
