# Generated by Django 5.2.14 on 2026-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_alter_account_comp_build_package_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annualreport',
            index=models.Index(fields=['website_new', '-report_year'], name='clients_ann_website_919a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='clienthealthscore',
            index=models.Index(fields=['website_new', '-calculated_at'], name='clients_cli_website_22388b_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorgapreport',
            index=models.Index(fields=['website_new', '-report_month'], name='clients_com_website_b28db5_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['website_new', '-report_month'], name='clients_int_website_f4d36c_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesuggestion',
            index=models.Index(fields=['website_new', '-generated_at'], name='clients_int_website_049281_idx'),
        ),
        migrations.AddIndex(
            model_name='uptimerecord',
            index=models.Index(fields=['website_new', 'checked_at'], name='clients_upt_website_5ef769_idx'),
        ),
    ]
