# Generated by Django 5.2.14 on 2026-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_annualreport_clients_ann_website_919a1d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='build_platform',
            field=models.CharField(choices=[('custom', 'Custom build — Aspired-hosted (Droplet)'), ('wordpress', 'WordPress — client-hosted (no Droplet)')], default='custom', help_text='WordPress sites are hosted by the client, so no Droplet is provisioned at intake completion.', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_build_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the package price on the build contract.', max_digits=10, null=True),
        ),
    ]
