# Generated by Django 5.2.14 on 2026-08-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_website_build_platform_website_custom_build_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginvoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invoices', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='onboardinginvoice',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invoices_new', to='clients.website'),
        ),
    ]
