# Generated by Django 5.2.14 on 2026-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_alter_onboardinginvoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Website Deposit'), ('final', 'Website Final Payment'), ('build', 'Website Payment'), ('maintenance', 'Maintenance'), ('social', 'Social Media'), ('hosting', 'Hosting'), ('addon', 'Add-on / Out-of-scope'), ('extra', 'Additional Payment'), ('other', 'Payment')], default='other', max_length=20),
        ),
    ]
