# Generated by Django 5.2.14 on 2026-09-17 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_alter_paymentrecord_kind'),
        ('public', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='public.city'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_hvac',
            field=models.BooleanField(default=False, help_text="HVAC industry work. Shown on the main portfolio and above the divider on city pages. Unchecked items appear on the 'other businesses' page and below the divider."),
        ),
    ]
