# Generated by Django 5.2.14 on 2026-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0062_casestudy_city_casestudy_is_hvac'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='is_concept',
            field=models.BooleanField(default=False, help_text="Demonstration/concept site, not a paid client project. Shows a visible 'Concept site' label on the card and detail page instead of presenting it as client work."),
        ),
    ]
