# Generated by Django 5.2.14 on 2026-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0065_whitehead_wellness_remove_em_dashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='stripe_build_installment_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
