# Generated by Django 5.2.14 on 2026-09-26 01:16

import clients.models
import clients.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_website_stripe_build_installment_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='moonieful_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='moonieful_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='moonieful_visible_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='moonieful_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(max_length=255, storage=clients.storage.private_document_storage, upload_to=clients.models.client_document_path),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='moonieful_document_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
