# Generated by Django 5.2.14 on 2026-09-26 03:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0068_moonieful_sites_intake_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='paid_at_signing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('pay_in_full', 'Build paid in full at signing'), ('installment', 'Build in 24 monthly installments'), ('none', 'No build (plan / hosting only)')], help_text='Blank on legacy 50/50 deposit contracts.', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='stripe_objects',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='website',
            name='build_installments_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='build_paid_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='stripe_build_installment_schedule_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='comp_build_package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('hvac_build', 'Website Build')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='comp_build_package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('hvac_build', 'Website Build')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='comp_package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred'), ('hvac_build', 'Website Build'), ('hvac_full_plan', 'Full Plan'), ('hvac_plan_paid_in_full', 'Full Plan — build paid upfront'), ('hvac_hosting_security', 'Hosting + Security')], help_text='DEPRECATED — use comp_build_package / comp_maintenance_package.', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred'), ('hvac_build', 'Website Build'), ('hvac_full_plan', 'Full Plan'), ('hvac_plan_paid_in_full', 'Full Plan — build paid upfront'), ('hvac_hosting_security', 'Hosting + Security')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('hvac_build', 'Website Build'), ('hvac_full_plan', 'Full Plan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contractservice',
            name='service_type',
            field=models.CharField(choices=[('build', 'Website Development'), ('maintenance', 'Full Plan / Website Maintenance'), ('hosting', 'Hosting + Security'), ('social', 'Social Media Marketing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Website Deposit'), ('final', 'Website Final Payment'), ('build', 'Website Payment'), ('installment', 'Website Build Installment'), ('refund', 'Refund'), ('maintenance', 'Maintenance'), ('social', 'Social Media'), ('hosting', 'Hosting'), ('addon', 'Add-on / Out-of-scope'), ('extra', 'Additional Payment'), ('other', 'Payment')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('hvac_build', 'Website Build'), ('hvac_full_plan', 'Full Plan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='lifecycle_status',
            field=models.CharField(blank=True, choices=[('inquiry', 'New inquiry — no contract'), ('contract_sent', 'Contract sent — unsigned'), ('contract_signed', 'Signed — awaiting payment'), ('deposit_paid', 'Paid — build can start'), ('in_build', 'In build'), ('live', 'Live')], help_text='Web-dev sales funnel state (set at booking + each step).', max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='package',
            field=models.CharField(blank=True, choices=[('essential_build', 'Essential Website Build'), ('premium_build', 'Premium Website Build'), ('maintenance_essentials', 'Maintenance — Essentials'), ('maintenance_growth', 'Maintenance — Growth'), ('maintenance_dominant', 'Maintenance — Dominant'), ('moonieful_referred', 'Moonieful Referred'), ('hvac_build', 'Website Build'), ('hvac_full_plan', 'Full Plan'), ('hvac_plan_paid_in_full', 'Full Plan — build paid upfront'), ('hvac_hosting_security', 'Hosting + Security')], max_length=30),
        ),
        migrations.AlterField(
            model_name='website',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_deposit', 'Awaiting Deposit'), ('deposit_paid', 'Deposit Paid'), ('installments_active', 'Installments Active'), ('fully_paid', 'Fully Paid')], default='awaiting_deposit', max_length=20),
        ),
        migrations.CreateModel(
            name='GuaranteeRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed — safe to retry')], default='processing', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retained_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('refunds', models.JSONField(blank=True, default=list)),
                ('cancelled_subscriptions', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_refunds', to='clients.account')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guarantee_refund', to='clients.contract')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_refunds', to='clients.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
