# Generated by Django 5.2.14 on 2026-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0069_hvac_billing_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='screenshot_mobile',
            field=models.ImageField(blank=True, help_text='Phone-width screenshot of the live site (390 px viewport). Captured by `capture_case_study_screenshots --mobile`; omitted from the page when empty.', upload_to='portfolio/'),
        ),
    ]
