# Generated by Django 5.2.14 on 2026-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_burgland_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='deep_dive',
            field=models.JSONField(blank=True, default=list, help_text='Technical sections (speed, mobile, SEO, security, accessibility, under the hood). Verifiable facts only.'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='scorecard',
            field=models.JSONField(blank=True, default=dict, help_text='Measured numbers only (Lighthouse, uptime, scan), with measured_on and method. Leave empty rather than estimate.'),
        ),
    ]
