# Generated by Django 5.2.14 on 2026-10-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_addon_location_pricing'),
        ('clients', '0074_food_trucks_count_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visible_plan_tiers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'maintenance'}, related_name='restricted_to_accounts', to='billing.servicetier'),
        ),
    ]
