# Generated by Django 5.2.14 on 2026-05-22 01:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_clientprofile_handoff_followup_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deploy_type', models.CharField(choices=[('fresh', 'Fresh Server Deploy'), ('redeploy', 'Code Update (Re-deploy)'), ('client', 'Client Site Deploy')], max_length=20)),
                ('server_ip', models.CharField(blank=True, max_length=50)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('github_repo', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('deployed_by', models.CharField(default='Zachery Long', max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_logs', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Deployment Log',
                'verbose_name_plural': 'Deployment Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
