# Generated by Django 5.2.14 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentlog',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_logs_new', to='clients.account'),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_logs_new', to='clients.website'),
        ),
    ]
