# Generated by Django 5.2.14 on 2026-06-09 22:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_deploymentlog_account_new_deploymentlog_website_new'),
        ('clients', '0032_contract_signed_content_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_command', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=80)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_logs', to='clients.clientprofile')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Assistant Log',
                'verbose_name_plural': 'AI Assistant Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
