# Generated by Django 5.2.14 on 2026-08-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_aiassistantlog'),
        ('clients', '0054_website_payment_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantlog',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_logs_new', to='clients.website'),
        ),
    ]
