# Generated by Django 5.2.14 on 2026-08-19 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_aiassistantlog_website_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('role_description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('run_interval_minutes', models.IntegerField(default=60)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low — cheapest, shallow reasoning'), ('medium', 'Medium — default'), ('high', 'High — the API default'), ('xhigh', 'Extra high — for hard agentic work'), ('max', 'Max — correctness over cost')], default='medium', help_text="Claude effort level for this agent's reasoning. Higher costs more per run. Raise once the daily digest justifies it.", max_length=10)),
                ('last_journal_entry', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Employee',
                'verbose_name_plural': 'AI Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIEmployeeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('reply_webhook', 'Reply')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('steps_used', models.IntegerField(default=0)),
                ('spend_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='admin_dashboard.aiemployee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_dashboard.aiemployee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEmployeeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=60)),
                ('tool_input', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(db_index=True, default=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='admin_dashboard.aiemployeerun')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['requires_approval', 'approved'], name='admin_dashb_require_1a8d8f_idx')],
            },
        ),
    ]
