# Generated by Django 5.2.14 on 2026-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_seed_prospect_ai_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployeerun',
            name='message_history',
            field=models.JSONField(blank=True, default=list, help_text='Raw Anthropic message list for this run. Reserved for future conversational replay; nothing reads it yet.'),
        ),
    ]
