# Generated by Django 5.2.17 on 2026-08-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_aiemployeerun_message_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployeeaction',
            name='executed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
