# Generated by Django 5.2.14 on 2026-08-29 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_aiemployeeaction_executed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiemployeerun',
            name='trigger',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('reply_webhook', 'Reply'), ('chat', 'Chat')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIEmployeeConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-titled from your first message; editable.', max_length=120)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='admin_dashboard.aiemployee')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aiemployeerun',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='admin_dashboard.aiemployeeconversation'),
        ),
    ]
