# Generated by Django 5.2.14 on 2026-08-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_aiemployeerun_trigger_aiemployeeconversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployeerun',
            name='partial_text',
            field=models.TextField(blank=True),
        ),
    ]
