# Generated by Django 5.2.14 on 2026-08-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_aiemployeerun_partial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployeeaction',
            name='progress',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
