# Generated by Django 5.2.14 on 2026-05-22 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_uptimealert_uptimerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBPSyncCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(choices=[('business_name', 'Business Name'), ('phone', 'Phone Number'), ('address', 'Address'), ('website', 'Website URL'), ('hours', 'Business Hours')], max_length=20)),
                ('website_value', models.TextField(blank=True)),
                ('gbp_value', models.TextField(blank=True)),
                ('is_mismatch', models.BooleanField(default=False)),
                ('flagged_for_fix', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_sync_checks', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'GBP Sync Check',
                'verbose_name_plural': 'GBP Sync Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=200)),
                ('target_url', models.URLField(blank=True, help_text='The page on their site targeting this keyword.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['keyword'],
                'unique_together': {('client', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('form_submit', 'Form Submission'), ('phone_click', 'Phone Number Click'), ('cta_click', 'CTA Button Click')], max_length=20)),
                ('element_id', models.CharField(blank=True, max_length=100)),
                ('element_text', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('event_timestamp', models.DateTimeField()),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['client', 'event_timestamp'], name='reporting_c_client__f008e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordRankRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateField(auto_now_add=True)),
                ('position', models.IntegerField(blank=True, help_text='1-100 ranking position; null = not in the top 100.', null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_records', to='reporting.trackedkeyword')),
            ],
            options={
                'ordering': ['-checked_at'],
                'unique_together': {('keyword', 'checked_at')},
            },
        ),
    ]
