# Generated by Django 5.2.14 on 2026-05-22 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clientprofile_testimonial_received_and_more'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=200)),
                ('target_keyword', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, help_text='Full HTML body.')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('word_count', models.IntegerField(default=0)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientChatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('greeting_message', models.TextField(default="Hi! I'm here to help answer questions about our services. How can I assist you?")),
                ('system_prompt', models.TextField(blank=True, help_text='Built from practice areas + FAQs.')),
                ('faq_text', models.TextField(blank=True, help_text='Raw FAQ notes used to build the system prompt.')),
                ('primary_color', models.CharField(default='#E8650A', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=12)),
                ('total_conversations', models.IntegerField(default=0)),
                ('leads_captured', models.IntegerField(default=0)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='clients.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=100)),
                ('messages', models.JSONField(default=list)),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('lead_captured', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reporting.clientchatbot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentFreshnessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pages_analyzed', models.IntegerField(default=0)),
                ('pages_needing_update', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshness_reports', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Content Freshness Report',
                'verbose_name_plural': 'Content Freshness Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('survey_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('score', models.IntegerField(blank=True, help_text='0-10; null = not yet responded.', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_action_taken', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'NPS Survey',
                'verbose_name_plural': 'NPS Surveys',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.DateField(help_text='First day of the reported month.')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('uptime_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_response_ms', models.IntegerField(blank=True, null=True)),
                ('keywords_on_page_1', models.IntegerField(default=0)),
                ('keywords_improved', models.IntegerField(default=0)),
                ('form_submissions', models.IntegerField(default=0)),
                ('phone_clicks', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('organic_traffic', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-report_month'],
                'unique_together': {('client', 'report_month')},
            },
        ),
    ]
