# Generated by Django 5.2.14 on 2026-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_blogpost_clientchatbot_chatbotconversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='requested_length',
            field=models.CharField(blank=True, choices=[('short', 'Short (~500w)'), ('medium', 'Medium (~800w)'), ('long', 'Long (~1200w)')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='requested_tone',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('conversational', 'Conversational'), ('authoritative', 'Authoritative')], default='professional', max_length=20),
        ),
    ]
