# Generated by Django 5.2.14 on 2026-05-24 00:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clientprofile_session_recording_enabled'),
        ('reporting', '0004_vulnerabilityscan_vulnerabilityfinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=100)),
                ('page_url', models.URLField(blank=True, max_length=2000)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('time_on_page_seconds', models.IntegerField(blank=True, null=True)),
                ('max_scroll_depth', models.IntegerField(blank=True, null=True)),
                ('scroll_milestones_hit', models.JSONField(blank=True, default=list)),
                ('exit_intent_fired', models.BooleanField(default=False)),
                ('click_heatmap', models.JSONField(blank=True, default=list)),
                ('form_submits', models.IntegerField(default=0)),
                ('phone_clicks', models.IntegerField(default=0)),
                ('cta_clicks', models.IntegerField(default=0)),
                ('raw_events', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sessions', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Page Session',
                'verbose_name_plural': 'Page Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='reporting_p_client__ee9a95_idx'), models.Index(fields=['client', 'session_id'], name='reporting_p_client__534135_idx')],
            },
        ),
    ]
