# Generated by Django 5.2.14 on 2026-05-24 00:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clientprofile_session_recording_enabled'),
        ('reporting', '0005_pagesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('page_url', models.URLField(blank=True, max_length=2000)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('recording_chunks', models.JSONField(blank=True, default=list)),
                ('viewport_width', models.IntegerField(blank=True, null=True)),
                ('viewport_height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('complete', 'Complete'), ('expired', 'Expired')], default='recording', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('estimated_size_kb', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recordings', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Session Recording',
                'verbose_name_plural': 'Session Recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status', '-created_at'], name='reporting_s_client__a65b14_idx'), models.Index(fields=['expires_at'], name='reporting_s_expires_c8918a_idx')],
            },
        ),
    ]
