# Generated by Django 5.2.14 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
        ('reporting', '0007_vulnerabilityscan_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='clientchatbot',
            name='website_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='contentfreshnessreport',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freshness_reports_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='gbpsynccheck',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_sync_checks_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='pagesession',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_sessions_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_recordings_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='trackedkeyword',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='vulnerabilityscan',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_scans_new', to='clients.website'),
        ),
    ]
