# Generated by Django 5.2.14 on 2026-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_vulnerabilityscan_been_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField()),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Claude API Usage',
                'verbose_name_plural': 'Claude API Usage',
                'ordering': ['-year_month', 'model'],
                'unique_together': {('year_month', 'model')},
            },
        ),
    ]
