# Generated by Django 5.2.14 on 2026-05-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_claudeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmarcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(help_text='Provider that sent the report (google.com, outlook.com, …).', max_length=120)),
                ('org_email', models.EmailField(blank=True, max_length=254)),
                ('report_id', models.CharField(max_length=200, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('policy_domain', models.CharField(max_length=120)),
                ('policy_p', models.CharField(blank=True, help_text='none / quarantine / reject', max_length=20)),
                ('policy_pct', models.IntegerField(blank=True, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('dmarc_pass', models.IntegerField(default=0, help_text='Messages that passed DMARC (DKIM aligned OR SPF aligned).')),
                ('dmarc_fail', models.IntegerField(default=0)),
                ('dkim_pass', models.IntegerField(default=0)),
                ('dkim_fail', models.IntegerField(default=0)),
                ('spf_pass', models.IntegerField(default=0)),
                ('spf_fail', models.IntegerField(default=0)),
                ('raw_xml', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'DMARC Report',
                'verbose_name_plural': 'DMARC Reports',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['-period_end'], name='reporting_d_period__67f163_idx')],
            },
        ),
        migrations.CreateModel(
            name='DmarcRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=0)),
                ('disposition', models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='none', max_length=20)),
                ('dkim_aligned', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('none', 'None'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('temperror', 'Temp error'), ('permerror', 'Perm error')], default='none', max_length=20)),
                ('spf_aligned', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('none', 'None'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('temperror', 'Temp error'), ('permerror', 'Perm error')], default='none', max_length=20)),
                ('header_from', models.CharField(blank=True, max_length=200)),
                ('dkim_domain', models.CharField(blank=True, max_length=200)),
                ('dkim_selector', models.CharField(blank=True, max_length=200)),
                ('dkim_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('none', 'None'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('temperror', 'Temp error'), ('permerror', 'Perm error')], default='none', max_length=20)),
                ('spf_domain', models.CharField(blank=True, max_length=200)),
                ('spf_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('none', 'None'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('temperror', 'Temp error'), ('permerror', 'Perm error')], default='none', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reporting.dmarcreport')),
            ],
            options={
                'verbose_name': 'DMARC Record',
                'verbose_name_plural': 'DMARC Records',
                'indexes': [models.Index(fields=['report', 'source_ip'], name='reporting_d_report__19c182_idx')],
            },
        ),
    ]
