# Generated by Django 5.2.14 on 2026-06-05 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_dmarcreport_dmarcrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisConnectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('by_category', models.JSONField(default=dict)),
                ('sample_raw', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Redis connection snapshot',
                'verbose_name_plural': 'Redis connection snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
