# Generated by Django 5.2.14 on 2026-06-10 02:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_clientprofile_gbp_location_name_and_more'),
        ('reporting', '0012_redisconnectionsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GbpOperatorToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, max_length=500)),
                ('provider_account_email', models.CharField(blank=True, max_length=255)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_error', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_operator_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GBP Operator Token',
                'verbose_name_plural': 'GBP Operator Tokens',
                'indexes': [models.Index(fields=['expires_at'], name='reporting_g_expires_3516bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GbpPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_month', models.DateField()),
                ('profile_views_search', models.IntegerField(default=0)),
                ('profile_views_maps', models.IntegerField(default=0)),
                ('call_clicks', models.IntegerField(default=0)),
                ('direction_requests', models.IntegerField(default=0)),
                ('website_clicks', models.IntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_performance_snapshots', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'GBP Performance Snapshot',
                'ordering': ['-snapshot_month'],
                'unique_together': {('client', 'snapshot_month')},
            },
        ),
        migrations.CreateModel(
            name='GbpReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_review_id', models.CharField(max_length=255)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_profile_photo_url', models.URLField(blank=True)),
                ('star_rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('review_created_at', models.DateTimeField(blank=True, null=True)),
                ('operator_reply_text', models.TextField(blank=True)),
                ('operator_reply_at', models.DateTimeField(blank=True, null=True)),
                ('needs_attention', models.BooleanField(default=False)),
                ('needs_attention_reason', models.CharField(blank=True, choices=[('', 'OK'), ('low_star', '≤3 stars'), ('unreplied', 'No reply'), ('flagged', 'Operator flagged')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_reviews', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'GBP Review',
                'ordering': ['-review_created_at', '-created_at'],
                'indexes': [models.Index(fields=['client', 'needs_attention'], name='reporting_g_client__bae8fd_idx')],
                'unique_together': {('client', 'provider_review_id')},
            },
        ),
    ]
