# Generated by Django 5.2.14 on 2026-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_gbpoperatortoken_gbpperformancesnapshot_gbpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='browser',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='os',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
