# Generated by Django 5.2.14 on 2026-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_website_payment_verification_note_and_more'),
        ('reporting', '0014_sessionrecording_browser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('client', 'report_month', 'website_new')},
        ),
    ]
