# Generated by Django 5.2.14 on 2026-08-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_website_payment_verification_note_and_more'),
        ('reporting', '0015_alter_monthlyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbpperformancesnapshot',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_performance_snapshots_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='gbpreview',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_reviews_new', to='clients.website'),
        ),
    ]
