# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
        ('reporting', '0016_gbpperformancesnapshot_website_new_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gbpperformancesnapshot',
            unique_together={('website_new', 'snapshot_month')},
        ),
        migrations.AlterUniqueTogether(
            name='gbpreview',
            unique_together={('website_new', 'provider_review_id')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('website_new', 'report_month')},
        ),
        migrations.AlterUniqueTogether(
            name='trackedkeyword',
            unique_together={('website_new', 'keyword')},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clientchatbot',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='contentfreshnessreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freshness_reports', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='gbpperformancesnapshot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_performance_snapshots', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='gbpreview',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_reviews', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='gbpsynccheck',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbp_sync_checks', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='npssurvey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='pagesession',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_sessions', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_recordings', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='trackedkeyword',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_scans', to='clients.clientprofile'),
        ),
    ]
