# Generated by Django 5.2.14 on 2026-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_annualreport_clients_ann_website_919a1d_idx_and_more'),
        ('reporting', '0017_alter_gbpperformancesnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['website_new', 'event_timestamp'], name='reporting_c_website_32bbec_idx'),
        ),
        migrations.AddIndex(
            model_name='gbpreview',
            index=models.Index(fields=['website_new', 'needs_attention'], name='reporting_g_website_287e45_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesession',
            index=models.Index(fields=['website_new', '-created_at'], name='reporting_p_website_11277c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesession',
            index=models.Index(fields=['website_new', 'session_id'], name='reporting_p_website_8795c9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['website_new', 'status', '-created_at'], name='reporting_s_website_d2a23f_idx'),
        ),
    ]
