# Generated by Django 5.2.17 on 2026-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_conversionevent_reporting_c_website_32bbec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISpendDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('request_count', models.IntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Spend (day)',
                'verbose_name_plural': 'AI Spend (daily)',
                'ordering': ['-day'],
            },
        ),
    ]
