# Generated by Django 5.2.14 on 2026-09-20 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_website_stripe_build_installment_subscription_id'),
        ('reporting', '0019_aispendday'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropletHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('ssh_unavailable', 'SSH Unavailable')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_disk', models.JSONField(blank=True, default=dict)),
                ('raw_memory', models.JSONField(blank=True, default=dict)),
                ('raw_services', models.JSONField(blank=True, default=dict)),
                ('raw_os_updates', models.JSONField(blank=True, default=dict)),
                ('raw_pip_audit', models.JSONField(blank=True, default=dict)),
                ('raw_security', models.JSONField(blank=True, default=dict)),
                ('disk_usage_percent', models.IntegerField(blank=True, null=True)),
                ('pending_os_updates_count', models.IntegerField(blank=True, null=True)),
                ('pip_audit_vulnerability_count', models.IntegerField(blank=True, null=True)),
                ('services_down', models.JSONField(blank=True, default=list)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('website_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='droplet_health_checks', to='clients.website')),
            ],
            options={
                'verbose_name': 'Droplet Health Check',
                'verbose_name_plural': 'Droplet Health Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
