# Generated by Django 5.2.14 on 2026-09-20 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_website_stripe_build_installment_subscription_id'),
        ('reporting', '0020_droplethealthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySummaryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.DateField(help_text='First day of the reported month.')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_critical_count', models.IntegerField(default=0)),
                ('open_high_count', models.IntegerField(default=0)),
                ('disk_usage_percent', models.IntegerField(blank=True, null=True)),
                ('pending_os_updates_count', models.IntegerField(blank=True, null=True)),
                ('pip_audit_vulnerability_count', models.IntegerField(blank=True, null=True)),
                ('services_down_count', models.IntegerField(default=0)),
                ('overall_status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('latest_droplet_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_summaries', to='reporting.droplethealthcheck')),
                ('latest_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_summaries', to='reporting.vulnerabilityscan')),
                ('website_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_summaries', to='clients.website')),
            ],
            options={
                'verbose_name': 'Security Summary Report',
                'verbose_name_plural': 'Security Summary Reports',
                'ordering': ['-report_month'],
                'unique_together': {('website_new', 'report_month')},
            },
        ),
    ]
