# Generated by Django 5.2.14 on 2026-09-26 03:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0068_moonieful_sites_intake_complete'),
        ('reporting', '0021_securitysummaryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='droplethealthcheck',
            name='file_integrity_changes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droplethealthcheck',
            name='raw_file_integrity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securitysummaryreport',
            name='scan_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securitysummaryreport',
            name='sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securitysummaryreport',
            name='uptime_incident_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitysummaryreport',
            name='uptime_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilityscan',
            name='raw_http',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FileIntegrityBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('file_count', models.IntegerField(default=0)),
                ('accepted_by', models.CharField(blank=True, max_length=150)),
                ('source_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_baselines', to='reporting.droplethealthcheck')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_integrity_baselines', to='clients.website')),
            ],
            options={
                'verbose_name': 'File Integrity Baseline',
                'verbose_name_plural': 'File Integrity Baselines',
                'ordering': ['-created_at'],
            },
        ),
    ]
