# Generated by Django 5.2.14 on 2026-05-25 00:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0025_clientprofile_maintenance_upsell_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRegistration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=253, unique=True)),
                ('tld', models.CharField(choices=[('com', '.com'), ('net', '.net'), ('org', '.org'), ('law', '.law'), ('legal', '.legal'), ('attorney', '.attorney')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending registration'), ('active', 'Active'), ('grace', 'In grace period (post-cancel)'), ('expired', 'Expired'), ('transferred_out', 'Transferred out'), ('cancelled', 'Cancelled'), ('failed', 'Registration failed')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('whois_privacy_enabled', models.BooleanField(default=True)),
                ('registrar_lock', models.BooleanField(default=True)),
                ('auto_renew_at_registrar', models.BooleanField(default=False)),
                ('nameservers', models.JSONField(blank=True, default=list)),
                ('epp_code_encrypted', models.TextField(blank=True)),
                ('epp_code_issued_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('pricing_tier_slug', models.CharField(blank=True, max_length=50)),
                ('auto_a_record_set_at', models.DateTimeField(blank=True, null=True)),
                ('last_api_call_at', models.DateTimeField(blank=True, null=True)),
                ('last_api_error', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_registrations', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('A', 'A — IPv4 address'), ('AAAA', 'AAAA — IPv6 address'), ('CNAME', 'CNAME — alias'), ('MX', 'MX — mail exchange'), ('TXT', 'TXT — text (SPF/DKIM/verification)'), ('URL', 'URL — HTTP 301 redirect'), ('URL301', 'URL301 — permanent redirect'), ('FRAME', 'FRAME — masked redirect')], max_length=8)),
                ('host', models.CharField(default='@', max_length=120)),
                ('value', models.TextField()),
                ('mx_priority', models.IntegerField(default=10)),
                ('ttl', models.IntegerField(default=1800)),
                ('auto_managed', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='domains.domainregistration')),
            ],
            options={
                'ordering': ['host', 'record_type'],
            },
        ),
        migrations.AddIndex(
            model_name='domainregistration',
            index=models.Index(fields=['client', 'status'], name='domains_dom_client__b70c12_idx'),
        ),
        migrations.AddIndex(
            model_name='domainregistration',
            index=models.Index(fields=['expires_at'], name='domains_dom_expires_985b69_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['domain', 'record_type'], name='domains_dns_domain__022a42_idx'),
        ),
    ]
