# Generated by Django 5.2.14 on 2026-05-25 01:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NamecheapConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sandbox_mode', models.BooleanField(default=True, help_text='When ON, every Namecheap API call hits the sandbox endpoint (api.sandbox.namecheap.com). When OFF, real registrations on api.namecheap.com that charge the account balance.')),
                ('last_toggled_at', models.DateTimeField(blank=True, null=True)),
                ('last_toggled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Namecheap configuration',
                'verbose_name_plural': 'Namecheap configuration',
            },
        ),
    ]
