# Generated by Django 5.2.14 on 2026-05-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_namecheapconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='parked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
