# Generated by Django 5.2.14 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
        ('domains', '0003_domainregistration_parked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistration',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='clients.account'),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='pointed_at_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='clients.website'),
        ),
    ]
