# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
        ('domains', '0004_domainregistration_account_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainregistration',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_registrations', to='clients.clientprofile'),
        ),
    ]
