# Generated by Django 5.2.14 on 2026-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_annualreport_clients_ann_website_919a1d_idx_and_more'),
        ('domains', '0005_alter_domainregistration_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domainregistration',
            index=models.Index(fields=['account_new', 'status'], name='domains_dom_account_bc4f2e_idx'),
        ),
    ]
