# Generated by Django 5.2.14 on 2026-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('performance_score', models.PositiveSmallIntegerField()),
                ('seo_score', models.PositiveSmallIntegerField()),
                ('best_practices_score', models.PositiveSmallIntegerField()),
                ('accessibility_score', models.PositiveSmallIntegerField()),
                ('issues', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Lead',
                'verbose_name_plural': 'Audit Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
