# Generated by Django 5.2.14 on 2026-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(help_text='One or two sentences. Used on the index card and as the meta description, so write it to earn a click.', max_length=300)),
                ('body', models.TextField(help_text="HTML. Headings should start at <h2> — the article title is the page's only <h1>.")),
                ('author_name', models.CharField(default='Zachery Long', max_length=120)),
                ('author_title', models.CharField(blank=True, default='Founder & Lead Developer, CISSP', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, help_text='Path of the commercial page this article supports, e.g. /pricing/. Rendered as the in-article CTA.', max_length=200)),
                ('related_label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
