# Generated by Django 5.2.17 on 2026-08-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlead',
            name='followup_1_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlead',
            name='followup_2_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlead',
            name='report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlead',
            name='unsubscribed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='auditlead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
