# Generated by Django 5.2.14 on 2026-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auditlead_followup_1_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('url_name', models.CharField(blank=True, max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=100)),
                ('hero_heading_html', models.CharField(blank=True, help_text='Full <h1> inner markup, e.g. \'Web Design for <span class="accent">San Antonio</span> Businesses\'.', max_length=300)),
                ('hero_lead', models.TextField(blank=True)),
                ('honesty_eyebrow', models.CharField(blank=True, default='Straight Up', max_length=100)),
                ('honesty_heading', models.CharField(blank=True, max_length=200)),
                ('honesty_subheading', models.CharField(blank=True, max_length=300)),
                ('honesty_html', models.TextField(blank=True, help_text="Raw HTML for this section's card(s).")),
                ('proof_eyebrow', models.CharField(blank=True, default='Proof', max_length=100)),
                ('proof_heading', models.CharField(blank=True, default='Work You Can Go And Look At', max_length=200)),
                ('proof_subheading', models.CharField(blank=True, max_length=300)),
                ('no_local_clients_note_html', models.TextField(blank=True)),
                ('value_tiles_eyebrow', models.CharField(blank=True, max_length=100)),
                ('value_tiles_heading', models.CharField(blank=True, max_length=200)),
                ('secondary_eyebrow', models.CharField(blank=True, max_length=100)),
                ('secondary_heading', models.CharField(blank=True, max_length=200)),
                ('secondary_html', models.TextField(blank=True)),
                ('cross_link_html', models.TextField(blank=True)),
                ('cta_heading', models.CharField(blank=True, max_length=200)),
                ('cta_body_html', models.TextField(blank=True)),
                ('schema_service_name', models.CharField(blank=True, max_length=200)),
                ('schema_description', models.TextField(blank=True)),
                ('schema_area_served', models.JSONField(blank=True, default=list, help_text='List of {"type": "City"|"AdministrativeArea"|"State", "name": "..."} for the Service schema\'s areaServed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
