# Generated by Django 5.2.14 on 2026-09-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='no_local_clients_note_html',
        ),
    ]
