# Generated by Django 5.2.14 on 2026-09-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_cities_remove_em_dashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_scope', models.TextField(blank=True, help_text='What the $2,000 build includes, one item per line. Blank hides the "What the build includes" list.')),
                ('review_platforms', models.TextField(blank=True, help_text='Job/field-service systems it connects to today.')),
                ('review_manual_trigger', models.TextField(blank=True, help_text='How it works with no job software (manual trigger).')),
                ('review_channel', models.TextField(blank=True, help_text='SMS, email, or both.')),
                ('review_message_costs', models.TextField(blank=True, help_text='Who pays per-message costs, if any.')),
                ('review_consent_model', models.TextField(blank=True, help_text='How the homeowner agreed to be contacted (TCPA).')),
                ('review_opt_out', models.TextField(blank=True, help_text='How recipients opt out (STOP / unsubscribe).')),
                ('review_multi_location', models.TextField(blank=True, help_text='How requests route for multi-location companies.')),
                ('review_setup_steps', models.TextField(blank=True, help_text='Setup steps, one per line.')),
                ('review_live_at_launch', models.TextField(blank=True, help_text='Is it live on launch day? What is needed?')),
                ('review_reporting', models.TextField(blank=True, help_text='What reporting the client receives.')),
                ('review_sample_message', models.TextField(blank=True, help_text='A real sample review-request message.')),
                ('continuity_backups', models.CharField(blank=True, help_text='Backup cadence, e.g. "Daily backups, kept for 30 days".', max_length=300)),
                ('continuity_outage_response', models.CharField(blank=True, help_text='Outage response target, e.g. "Work starts on an outage within 1 hour".', max_length=300)),
                ('founding_client_enabled', models.BooleanField(default=False)),
                ('founding_client_headline', models.CharField(blank=True, max_length=200)),
                ('founding_client_offer', models.TextField(blank=True, help_text='What the founding client gets, one item per line.')),
                ('founding_client_ask', models.TextField(blank=True, help_text='What Aspired asks in return, one item per line.')),
                ('demo_enabled', models.BooleanField(default=False)),
                ('demo_title', models.CharField(blank=True, max_length=200)),
                ('demo_url', models.URLField(blank=True)),
                ('demo_description', models.TextField(blank=True)),
                ('google_reviews_url', models.URLField(blank=True, help_text="Aspired's own Google reviews link.")),
                ('cissp_member_number', models.CharField(blank=True, help_text='(ISC)2 member number. Blank shows "member number on request".', max_length=40)),
                ('phone_accepts_sms', models.BooleanField(default=False, help_text='The 210 number receives texts ("Call or text").')),
                ('session_recording_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('audit_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('faq_finance_with_hosting', models.TextField(blank=True, help_text='"Can I finance the build and take the $45 plan?"')),
                ('faq_url_migration', models.TextField(blank=True, help_text='"Do you carry over my old page URLs?"')),
                ('faq_client_time', models.TextField(blank=True, help_text='"How much of my time does a build take?"')),
                ('faq_travel_fee', models.TextField(blank=True, help_text='"Is there a travel fee for in-person meetings?"')),
                ('faq_pause_plan', models.TextField(blank=True, help_text='"Can I pause the Full Plan in slow months?"')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content (owner inputs)',
                'verbose_name_plural': 'Site content (owner inputs)',
            },
        ),
    ]
