# Generated by Django 5.2.14 on 2026-09-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_sitecontent_owner_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Reachable by URL but noindexed, unlisted, and shown with an "archived" notice.'),
        ),
    ]
