# Generated by Django 5.2.14 on 2026-09-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_rename_full_plan_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='google_review_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Google reviews Aspired itself has. Blank keeps the plain "Read our Google reviews" link.', null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='google_review_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Aspired's own Google rating, e.g. 5.0. Shown only with a review count.", max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='ms_university',
            field=models.CharField(blank=True, help_text='Institution that issued the M.S. in Cybersecurity. Blank shows "available on request" on the About page.', max_length=120),
        ),
    ]
