# Generated by Django 5.2.14 on 2026-05-22 01:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_clientprofile_handoff_followup_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('pin_set', 'PIN Set'), ('pin_verified', 'PIN Verified — Vault Unlocked'), ('pin_failed', 'PIN Failed'), ('pin_locked', 'Vault Locked — Too Many Attempts'), ('credential_viewed', 'Credential Viewed'), ('credential_created', 'Credential Created'), ('credential_updated', 'Credential Updated'), ('credential_deleted', 'Credential Deleted')], max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('credential_label', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vault Access Log',
                'verbose_name_plural': 'Vault Access Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin_hash', models.CharField(blank=True, max_length=256)),
                ('encryption_salt', models.BinaryField(default=b'', max_length=32)),
                ('pin_set', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vault Configuration',
                'verbose_name_plural': 'Vault Configuration',
            },
        ),
        migrations.CreateModel(
            name='ClientVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text="General plaintext notes about this client's setup (not sensitive).")),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['client__firm_name'],
            },
        ),
        migrations.CreateModel(
            name='VaultCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('server', 'Server / Hosting'), ('domain', 'Domain Registrar'), ('google', 'Google Account'), ('social', 'Social Media'), ('email', 'Email / DNS'), ('stripe', 'Stripe / Payments'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('username_encrypted', models.TextField(blank=True)),
                ('password_encrypted', models.TextField(blank=True)),
                ('url_encrypted', models.TextField(blank=True)),
                ('notes_encrypted', models.TextField(blank=True)),
                ('username_hint', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('visible_to_client', models.BooleanField(default=False)),
                ('client_username_plain', models.TextField(blank=True)),
                ('client_password_plain', models.TextField(blank=True)),
                ('client_url_plain', models.URLField(blank=True)),
                ('client_notes_plain', models.TextField(blank=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='vault.clientvault')),
            ],
            options={
                'verbose_name': 'Vault Credential',
                'verbose_name_plural': 'Vault Credentials',
                'ordering': ['category', 'sort_order', 'label'],
            },
        ),
    ]
