# Generated by Django 5.2.14 on 2026-05-22 19:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientprofile_address_clientprofile_city_and_more'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='is_ssh_credential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_auth_type',
            field=models.CharField(blank=True, choices=[('password', 'Password'), ('private_key', 'Private Key')], default='password', max_length=12),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_host_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_key_passphrase_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_private_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='ssh_username_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='totp_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='totp_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vaultaccesslog',
            name='action',
            field=models.CharField(choices=[('pin_set', 'PIN Set'), ('pin_verified', 'PIN Verified — Vault Unlocked'), ('pin_failed', 'PIN Failed'), ('pin_locked', 'Vault Locked — Too Many Attempts'), ('credential_viewed', 'Credential Viewed'), ('credential_created', 'Credential Created'), ('credential_updated', 'Credential Updated'), ('credential_deleted', 'Credential Deleted'), ('ssh_totp_setup', 'SSH TOTP Configured'), ('ssh_totp_verified', 'SSH TOTP Verified — Session Started'), ('ssh_connected', 'SSH Terminal Connected'), ('ssh_disconnected', 'SSH Terminal Disconnected')], max_length=30),
        ),
        migrations.CreateModel(
            name='ServerCommandLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('logs', 'Logs'), ('monitoring', 'Monitoring'), ('deploy', 'Deploy'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='vault.vaultcredential')),
            ],
            options={
                'verbose_name': 'Server Command',
                'verbose_name_plural': 'Server Commands',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SSHSessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('totp_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('commands_executed', models.JSONField(default=list)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_sessions', to='clients.clientprofile')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_sessions', to='vault.vaultcredential')),
            ],
            options={
                'verbose_name': 'SSH Session Log',
                'verbose_name_plural': 'SSH Session Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
