# Generated by Django 5.2.14 on 2026-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultcredential_is_ssh_credential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='encrypted_with_server_key',
            field=models.BooleanField(default=False),
        ),
    ]
