# Generated by Django 5.2.14 on 2026-05-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultcredential_encrypted_with_server_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultcredential',
            name='totp_configured',
        ),
        migrations.RemoveField(
            model_name='vaultcredential',
            name='totp_secret_encrypted',
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='totp_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='totp_secret_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
