# Generated by Django 5.2.14 on 2026-05-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_remove_vaultcredential_totp_configured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultconfig',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
