# Generated by Django 5.2.14 on 2026-05-23 14:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientprofile_is_tester'),
        ('vault', '0005_vaultconfig_recovery_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('conversation', models.JSONField(blank=True, default=list)),
                ('commands_executed', models.JSONField(blank=True, default=list)),
                ('dangerous_commands_approved', models.JSONField(blank=True, default=list)),
                ('dangerous_commands_denied', models.JSONField(blank=True, default=list)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_sessions', to='clients.clientprofile')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_sessions', to='vault.vaultcredential')),
            ],
            options={
                'verbose_name': 'AI Ops Session',
                'verbose_name_plural': 'AI Ops Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
