# Generated by Django 5.2.14 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_account_onboardinginvoice_account_new_and_more'),
        ('vault', '0006_opssession'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvault',
            name='account_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_new', to='clients.account'),
        ),
        migrations.AddField(
            model_name='opssession',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_sessions_new', to='clients.account'),
        ),
        migrations.AddField(
            model_name='opssession',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_sessions_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='sshsessionlog',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_sessions_new', to='clients.account'),
        ),
        migrations.AddField(
            model_name='sshsessionlog',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_sessions_new', to='clients.website'),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='website_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_credentials_new', to='clients.website'),
        ),
    ]
