# Generated by Django 5.2.14 on 2026-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_credential_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='created_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
