# Generated by Django 5.2.14 on 2026-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_vaultcredential_created_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('normal', 'Ended by operator'), ('killed', 'Killed from the sessions list'), ('idle_timeout', 'Auto-closed after inactivity')], help_text='Blank while the session is still open.', max_length=20),
        ),
        migrations.AddField(
            model_name='opssession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
