# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
        ('vault', '0010_opssession_end_reason_opssession_last_activity_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvault',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='clients.clientprofile'),
        ),
    ]
