# Generated by Django 5.2.14 on 2026-09-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_alter_clientvault_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='automation_access_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='automation_key_last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='automation_ssh_private_key_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
