# Generated by Django 5.2.14 on 2026-08-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_website_payment_verification_note_and_more'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='account_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts_new', to='clients.account'),
        ),
    ]
