# Generated by Django 5.2.14 on 2026-08-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_alter_annualreport_unique_together_and_more'),
        ('social', '0002_scheduledpost_account_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='clients.clientprofile'),
        ),
    ]
