# Generated by Django 5.2.14 on 2026-06-08 03:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('social_media', 'Social Media'), ('website_design', 'Website Design')], max_length=20)),
                ('tier_slug', models.CharField(max_length=50)),
                ('welcome_seen', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_section', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'product_type', 'tier_slug')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('skipped', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='onboarding.onboarding')),
            ],
            options={
                'ordering': ['question_key'],
                'unique_together': {('onboarding', 'question_key')},
            },
        ),
    ]
