# Generated by Django 5.2.14 on 2026-06-08 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupTodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('vault_credential', 'Vault credential'), ('google_access', 'Google service access'), ('hosting_moveover', 'Hosting move-over'), ('manual', 'Manual task')], default='vault_credential', max_length=30)),
                ('credential_category', models.CharField(blank=True, max_length=20)),
                ('credential_type', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('deeplink_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_completed_by', models.CharField(blank=True, max_length=80)),
                ('reminder_3_sent', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('reminder_14_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
