# Generated by Django 5.2.14 on 2026-06-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_passwordsetuptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSectionDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('social_media', 'Social Media'), ('website_design', 'Website Design')], db_index=True, max_length=20)),
                ('key', models.CharField(help_text='Stable code, e.g. M1 / S2. Unique per product type.', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('intro', models.TextField(blank=True, help_text='Optional blurb under the section title.')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tier_visibility', models.JSONField(blank=True, default=list, help_text='List of tier slugs this section shows for. Empty = all tiers. e.g. ["social-standard","social-full"].')),
                ('requires_hosting_moveover', models.BooleanField(default=False, help_text='Only show if the client bought the hosting move-over (maintenance migration section).')),
                ('skip_if_completed_intake', models.BooleanField(default=False, help_text='Hide if the client already completed the website intake (we already have these answers).')),
                ('is_channel_template', models.BooleanField(default=False, help_text="Social only — repeat this section's questions once per channel in the tier (keys become channel_<n>_<key>).")),
            ],
            options={
                'verbose_name': 'Onboarding Section',
                'ordering': ['product_type', 'sort_order', 'key'],
                'unique_together': {('product_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestionDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable code that persists answers. For channel-template sections use the base key (e.g. "platform").', max_length=80)),
                ('label', models.CharField(max_length=300)),
                ('qtype', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('select', 'Dropdown'), ('bool', 'Yes / No'), ('cred_access', 'Credential access')], default='text', max_length=20)),
                ('help', models.CharField(blank=True, max_length=400)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('skip_allowed', models.BooleanField(default=True)),
                ('rows', models.IntegerField(blank=True, help_text='Rows for a long-text box.', null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Dropdown options as [["value","Label"], ...].')),
                ('cred_category', models.CharField(blank=True, max_length=40)),
                ('cred_type', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onboarding.onboardingsectiondef')),
            ],
            options={
                'verbose_name': 'Onboarding Question',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
